swagger: '2.0'
info:
  title: Very simple energy API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /tick:
    get:
      summary: Signal one tick (13.3Wh)
      operationId: api.tick
      responses:
        200:
          description: Successful tick

  /:
    get:
      summary: Get an html website to show some info
      operationId: api.render_html
      responses:
        200:
          description: Successful request

  /lcdinfo:
    get:
      summary: Get today's energy consumption to show on an lcd screen
      operationId: api.get_lcd_info
      responses:
        200:
          description: Successful response